### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xb7' in position 8: ordinal not in range(128)

### ISSUE THREAD

**Issue by ritzenthaler** [zulip/zulip-archive#45] opened 2020-11-28 11:50 UTC
Hello! I've tried to run the code but I get the error in the title which prevent the program to end (at least I don't get any archive following the link). I'm no specialist but I really followed the instructions precisely and look at various places how to fix it myself but without success.  Any help would be appreciated! Thanks :)

**Comment by mattecapu** [comment] 2020-12-14 16:21
Hi everyone, I'm also getting the same error. I think the culprit is one of my streams as a unicode character in the name.
For now I resorted to renaming it, it would be great to support unicode though.

**Comment by rht** [comment] 2021-01-23 07:10
Can you post the line number of the error? Preferably the full traceback.

**Comment by refeed** [comment] 2022-07-04 09:50
I think this has been solved by https://github.com/zulip/zulip-archive/blob/5da606feac0fa69445de717c406f79dd81e82e59/lib/url.py#L75

**Comment by rht** [comment] 2022-07-04 12:36
But that line (`s.encode("ascii", "ignore").decode("utf-8")`) was already present even before this issue was reported: https://github.com/zulip/zulip-archive/blame/b9a15835a09dac9338c1cb21f359976fcbf41f2d/lib/url.py.

**Comment by gnprice** [comment] 2022-07-05 19:58
@refeed For trying to debug this issue, I think a good next step would be to try to reproduce using the detail @mattecapu provided: try making a stream with a non-ASCII character in its name and running zulip-archive on that. From the thread so far, it seems likely that it doesn't have anything to do with that particular line.

Meanwhile for anyone who's encountering this issue: a very helpful next piece of information to provide would be the full stack trace / traceback.

**Comment by refeed** [comment] 2022-07-08 10:34
@gnprice yup, I had tried to reproduce using the detail @mattecapu given, but still didn't get any error.

**Comment by rht** [comment] 2022-07-09 09:30
If you look at the oldest version of `sanitize()`, it has existed since the earliest version of the code: https://github.com/zulip/zulip-archive/blame/063cb43e0266fba0a5f9679cb812c85279cbc85f/lib/common.py. That bug must be caused by a different code path elsewhere.

@refeed have you tried by creating an archive of an organization that has a stream with non-ASCII chars?

**Comment by refeed** [comment] 2022-07-09 10:54
@rht yes, I did
![image](https://user-images.githubusercontent.com/20320125/178102557-7a64a7d3-0536-474e-b083-6f4096362156.png)

I think you are correct, when I looked at that git blame, I saw an `str.encode()` without `ignore` argument, that could be the cause I think
https://github.com/zulip/zulip-archive/blame/063cb43e0266fba0a5f9679cb812c85279cbc85f/lib/common.py#L22

**Comment by rht** [comment] 2022-07-09 11:59
Since we can't reproduce the issue, and OP has been nonresponsive, I think we should just close the issue.

**Comment by gnprice** [comment] 2022-07-13 02:51
OK, great. Because we've tried reproducing the issue with the information we have and everything seems to work, and we've looked at the implementation and it seems fine in a couple of the most likely spots where the issue might be, it makes sense to close the issue. Thanks @refeed and @rht for the investigation!

It's still a bit mysterious because, as we found above, there haven't been any code changes that seem like they would have fixed it. So it's still fairly likely that the issue still exists, just in some other area of code or some other scenario that we haven't thought of.

@ritzenthaler, @mattecapu, or anyone else: if you do see any symptom like this again, please do reply here (or file a new issue) and we can reopen the issue and take a look. As discussed above, the full stack trace / traceback would be a very helpful set of details to add.

**Closed by gnprice** 2022-07-13 02:51 UTC
