### ISSUE TITLE
error in error handling

### ISSUE THREAD

**Issue by c-cube** [zulip/zulip-archive#31] opened 2020-01-24 18:55 UTC
in populate.py, safe_request, `rsp['result']` isn't defined (at least for me). So instead of having an error about an invalid key (I was using the wrong email) I got errors about `rsp`.

**Comment by timabbott** [comment] 2020-01-26 06:50
@c-cube can you print(rsp) in that code path when you see this?  I'd like to make sure we know what the actual error was.  My guess is the issue is we're failing to check the HTTP status code before trying to look at the result JSON, but I'd like to confirm that.

**Comment by c-cube** [comment] 2020-01-26 19:36
I already did that, and it was an invalid auth token error (I put the wrong email in). 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by showell** [comment] 2020-01-29 00:16
@c-cube Thanks for the error report!  I have pushed a fix to master.

**Closed by showell** 2020-01-29 00:16 UTC

**Comment by showell** [comment] 2020-01-29 00:25
https://github.com/zulip/zulip-archive/commit/ec0d3a5f7155dba132f66a914d7c29a4ffb2d65c
